### ISSUE TITLE
create automatic attribution sentence (like wikimedia does )

### ISSUE THREAD

**Issue by gwenfranck** [oSoc18/open-flandria#22]
like this: https://commons.wikimedia.org/wiki/File:%22Art_of_Flight%22_informational_display.jpg

**Comment by awildbrysen** [comment]
So the idea would be to get something like this? 
```By <user> [<license of the image>], from Open Flandria.```

**Comment by gwenfranck** [comment]
I would say: Picture by <name> , [<license image>], found on Open Flandria [<exact link>]

**Comment by gwenfranck** [comment]
first brackets, ok , last brackets: include exact location link

**Comment by awildbrysen** [comment]
This has been added
